# Generated by Django 4.1 on 2022-10-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_end_time_alter_company_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
