# Generated by Django 4.1 on 2022-10-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_worktime_end_time_alter_worktime_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='created_at',
            field=models.DateField(),
        ),
    ]
