# Generated by Django 4.1 on 2022-10-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_worktime_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
