# Generated by Django 4.1 on 2022-10-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_worktime_created_at_alter_worktime_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
