# Generated by Django 4.1 on 2022-10-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_worktime_end_time_alter_worktime_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
