# Generated by Django 4.1 on 2022-10-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_worktime_end_time_alter_worktime_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='worked',
            field=models.IntegerField(null=True),
        ),
    ]
