# Generated by Django 4.1 on 2022-10-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_worktime_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='worked',
            field=models.FloatField(null=True),
        ),
    ]
