# Generated by Django 4.1 on 2022-10-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_worktime_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='on_time',
            field=models.BooleanField(null=True),
        ),
    ]
