# Generated by Django 4.1 on 2022-10-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_worktime_on_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='late',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='on_time',
            field=models.IntegerField(null=True),
        ),
    ]
