# Generated by Django 4.1 on 2022-10-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_worktime_late_remove_worktime_on_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='late',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='on_time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
