# Generated by Django 4.1 on 2022-10-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_member_late_alter_member_on_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='late',
        ),
        migrations.RemoveField(
            model_name='member',
            name='on_time',
        ),
        migrations.AddField(
            model_name='worktime',
            name='on_time',
            field=models.BooleanField(null=True),
        ),
    ]
