# Generated by Django 4.1 on 2022-10-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_member_late_remove_member_on_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='secret_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
