# Generated by Django 4.1 on 2022-10-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_member_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='totalWorkTime',
            field=models.IntegerField(null=True),
        ),
    ]
