# Generated by Django 4.1 on 2022-10-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_member_totalworktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='totalWorkTime',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
